# !!! Docker Compose for Local Development Only
version: "3.9"
services:
  keycloak_mailhog:
    image: mailhog/mailhog
    container_name: keycloak_mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
  keycloak_pgsql:
    container_name: keycloak_pgsql
    image: postgres
    volumes:
      - ./pgsql:/var/lib/postgresql/data
    ports:
      # HOST:CONTAINER
      - "5437:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_pass
  keycloak:
    container_name: keycloak
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      # HOST:CONTAINER
      - "8037:8443"
    depends_on:
      - keycloak_pgsql
    environment:
      # Server
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8037
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # Database
      KC_DB_URL: jdbc:postgresql://keycloak_pgsql:5432/keycloak
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_pass
