# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/explore-keycloak',
                'doc_host': 'https://tstec-polypoly.github.io',
                'git_url': 'https://github.com/tstec-polypoly/explore-keycloak',
                'lib_path': 'explore_keycloak'},
  'syms': {'explore_keycloak.core': {'explore_keycloak.core.foo': ('core.html#foo', 'explore_keycloak/core.py')}}}